/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package TreeIntersection;

import TreeIntersection.structure.HashMap;
import com.sun.source.tree.BinaryTree;

import java.util.ArrayList;

import static java.lang.Character.compare;

public class App {


    public static void main(String[] args) {

    }

}
