/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package insertion.sort;

import org.junit.jupiter.api.Test;

import static insertion.sort.App.insertionSort;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void insertionSortTest() {

        int[] expectedArr = {1,2,3,4,5};
        int[] testedArr= {3,2,1,5,4};

        assertArrayEquals(expectedArr,insertionSort(testedArr));
    }

    @Test
    void insertionSortEmptyTest() {

        int[] expectedArr = {};
        int[] testedArr= {};

        assertArrayEquals(expectedArr,insertionSort(testedArr));
    }


    @Test
    void insertionSortOneElementTest() {

        int[] expectedArr = {5};
        int[] testedArr= {5};

        assertArrayEquals(expectedArr,insertionSort(testedArr));
    }

    @Test
    void insertionSortSortedTest() {

        int[] expectedArr = {5,6,7,8};
        int[] testedArr= {5,6,7,8};

        assertArrayEquals(expectedArr,insertionSort(testedArr));
    }
    @Test
    void insertionSortFrequentElementsTest() {

        int[] expectedArr = {4,4,4,5,5,5,6};
        int[] testedArr= {5,4,5,4,5,4,6};

        assertArrayEquals(expectedArr,insertionSort(testedArr));
    }

}
