/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quick.sort;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static quick.sort.App.quickSort;

class AppTest {
    @Test
    void quickSortTest() {
        int[] expectedArr = {1,2,3,4,5};
        int[] testedArr ={2,4,3,5,1};

        assertArrayEquals(expectedArr,quickSort(testedArr,0,testedArr.length-1));
    }

    @Test
    void quickSortSortedArrTest() {
        int[] expectedArr = {1,2,3,4,5};
        int[] testedArr ={1,2,3,4,5};

        assertArrayEquals(expectedArr,quickSort(testedArr,0,testedArr.length-1));
    }

    @Test
    void quickSortEmptyArrTest() {
        int[] expectedArr = {};
        int[] testedArr ={};

        assertArrayEquals(expectedArr,quickSort(testedArr,0,testedArr.length-1));
    }
}
