/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class App {

    public static void main(String[] args) {
        BinarySearchTree <Double> binarySearchTree = new BinarySearchTree<>();
        binarySearchTree.add(5);
        binarySearchTree.add(4);
        binarySearchTree.add(6);
        binarySearchTree.add(3);
        System.out.println(binarySearchTree.preOrder(binarySearchTree.root));
        System.out.println(binarySearchTree.inOrder(binarySearchTree.root));
        System.out.println(binarySearchTree.postOrder(binarySearchTree.root));
    }
}
