/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hashtable;

import hashtable.data.HashNode;
import hashtable.structure.HashMap;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void HashMapTesting() {
        HashMap <String , String > testHashMap = new HashMap<>();
        testHashMap.set("Jordan","Amman");
        testHashMap.set("Egypt","Cairo");

        assertEquals("Amman",testHashMap.get("Jordan"));
    }
    @Test void HashMapTestingEditingValue() {
        HashMap <String , String > testHashMap = new HashMap<>();
        testHashMap.set("Jordan","Irbid");
        testHashMap.set("Jordan","Amman");
        testHashMap.set("Egypt","Cairo");

        assertEquals("Amman",testHashMap.get("Jordan"));
    }
//   4.Successfully returns a list of all unique keys that exist in the hashtable
//    @Test void HashMapTestingKeys() {
//        HashMap <String , String > testHashMap = new HashMap<>();
//        testHashMap.set("Jordan","Irbid");
//        testHashMap.set("Jordan","Amman");
//        testHashMap.set("Egypt","Cairo");
//        ArrayList<String> expected = new ArrayList<String>();
//        expected.add("Jordan");
//        expected.add("Egypt");
//
//        assertArrayEquals(testHashMap.keys(),expected);
//    }
@Test void HashMapTestingNull() {
    HashMap <String , String > testHashMap = new HashMap<>();
    testHashMap.set("Jordan","Irbid");
    testHashMap.set("Jordan","Amman");
    testHashMap.set("Egypt","Cairo");

    assertEquals(null,testHashMap.get("Syria"));
}
//Successfully handle a collision within the hashtable
    @Test void HashMapTestingIll() {
        HashMap <String , Integer > testHashMap = new HashMap<>();
        testHashMap.set("Palestine",1);
        testHashMap.set("Jordan",2);
        testHashMap.set("Egypt",2);
        testHashMap.set("Syria",3);
        testHashMap.set("Lebanon",4);
        testHashMap.set("Morocco",5);
        testHashMap.set("Libya",6);
        testHashMap.set("Algeria",7);
        testHashMap.set("Tunisia",8);
        testHashMap.set("Turkish",9);
        testHashMap.set("Italy",18);
        testHashMap.set("France",28);

        assertEquals(12 , testHashMap.getSize());
    }


}
