/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.util.stream.IntStream;
import java.util.stream.Stream;

public class App {
    public static int[] mergeSort( int[]arr ) {

        int arrLength = arr.length;
        int mid = arrLength/2;
        int[] left = new int[mid];
        int[] right = new int[arrLength-mid];
        if(arrLength>1)
        {
            for(int i=0;i<mid;i++)
            {
                left[i]=arr[i];
            }

            for(int i=mid;i<arrLength;i++)
            {
                right[i-mid]=arr[i];
            }

            mergeSort(left);

            mergeSort(right);

            merge(left, right, arr);
        }

        return arr ;
    }

    public static void merge (int[] left , int[] right , int[] arr){
        int i=0 ,j=0,k=0;
        while(i< left.length&&j< right.length){
            if(left[i]<=right[j]){
                arr[k]=left[i];
                i++;
            }
            else
            {
                arr[k]=right[j];
                j++;
            }
            k++;
        }
        if(i== left.length){
            while (j < right.length) {
                arr[k] = right[j];
                k++; j++;
            }
        }
        else
        {
            while (i < left.length) {
                arr[k] = left[i];
                k++; i++;
            }
        }
    }

    public static void main(String[] args) {
    }


    public static int[] quickSort(int[] arr, int left,int right){

    if (left < right)
    {
        // Partition the array by setting the position of the pivot value
        int position=Partition(arr, left, right);
        // Sort the left
        quickSort(arr, left, position - 1);
        // Sort the right
        quickSort(arr, position + 1, right);

    }
    return arr;

}
public static int Partition(int[] arr,int left,int right)
{
    // set a pivot value as a point of reference
    int pivot= arr[right];
    // create a variable to track the largest index of numbers lower than the defined pivot
    int low = left - 1;
    for (int i =left ;i< right;i++) {
        if (arr[i] <= pivot) {
            low++;
            Swap(arr, i, low);
        }

    }
        // place the value of the pivot location in the middle.
        // all numbers smaller than the pivot are on the left, larger on the right.
        Swap(arr, right, low + 1);
        // return the pivot index point
        return low + 1;

}
public static void Swap(int[] arr,int i,int low){
    int temp;
    temp = arr[i];
    arr[i]= arr[low];
    arr[low]= temp;
}

}

