/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package merge.sort;

import java.util.stream.IntStream;
import java.util.stream.Stream;

public class App {
    public static int[] mergeSort( int[]arr ) {

        int arrLength = arr.length;
        int mid = arrLength/2;
        int[] left = new int[mid];
        int[] right = new int[arrLength-mid];
        if(arrLength>1)
        {

            for(int i=0;i<mid;i++)
            {
                left[i]=arr[i];
            }

            for(int i=mid;i<arrLength;i++)
            {
                right[i-mid]=arr[i];
            }

            mergeSort(left);

            mergeSort(right);

            merge(left, right, arr);

        }

        return arr ;
    }

    public static void merge (int[] left , int[] right , int[] arr){
        int i=0 ,j=0,k=0;
        while(i< left.length&&j< right.length){
            if(left[i]<=right[j]){
                arr[k]=left[i];
                i++;
            }
            else
            {
                arr[k]=right[j];
                j++;
            }
            k++;
        }
        if(i== left.length){
            while (j < right.length) {
                arr[k] = right[j];
                k++; j++;
            }
        }
        else
        {
            while (i < left.length) {
                arr[k] = left[i];
                k++; i++;
            }
        }
    }

    public static void main(String[] args) {
    }
}

