/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

//    linkedList <Integer> myFirstList = new linkedList<Integer>();

    @Test
    void testInsert() {

//        myFirstList.insert(1);
//        myFirstList.insert(2);
//        myFirstList.insert(3);
//        myFirstList.insert(4);
//        myFirstList.insert(5);

//        assertEquals(,myFirstList);
    }


}
