/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linked.list;

public class App {
    public static void main(String[] args) {

        linkedList <Boolean> myFirstList = new linkedList<Boolean>();

        myFirstList.Insert(true);
        myFirstList.Insert(true);
        myFirstList.Insert(true);
        myFirstList.Insert(true);
        myFirstList.Insert(true);

        System.out.println(myFirstList.includes(true));
        System.out.println(myFirstList.includes(false));
        System.out.println(myFirstList.toString());
        myFirstList.Insert(false);
        System.out.println(myFirstList.includes(false));


        System.out.println(myFirstList.toString());


    }
}
